# Generated by Django 5.1.2 on 2024-10-14 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_billet', models.CharField(choices=[('VVIP', 'Very Very Important Person'), ('VIP', 'Very Important Person'), ('STANDARD', 'Standard')], max_length=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('date_concert', models.DateTimeField()),
                ('nombre_disponible', models.PositiveIntegerField()),
            ],
        ),
    ]
