# Generated by Django 5.1.2 on 2024-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
